### ISSUE TITLE
cannot install it 

### ISSUE THREAD

**Issue by tekno31** [reverse-shell/routersploit#114]
its show me that when i try to open it on ubntu 14 

> raceback (most recent call last):
  File "./rsf.py", line 3, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/home/tekno/routersploit/routersploit/__init__.py", line 1, in <module>
    from routersploit.utils import (
  File "/home/tekno/routersploit/routersploit/utils.py", line 35, in <module>
    requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.InsecureRequestWarning)
AttributeError: 'module' object has no attribute 'packages'
tekno@tekno-Gateway-Phantom:~/routersploit$ python rsf.py
Traceback (most recent call last):
  File "rsf.py", line 3, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/home/tekno/routersploit/routersploit/__init__.py", line 1, in <module>
    from routersploit.utils import (
  File "/home/tekno/routersploit/routersploit/utils.py", line 35, in <module>
    requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.InsecureRequestWarning)
AttributeError: 'module' object has no attribute 'packages'

**Comment by nixawk** [comment]
```
$ cd /path/to/routersploit && sudo pip -r requirements.txt
```

If you have also some problems, please redirect to: https://github.com/reverse-shell/routersploit/issues/101
