### ISSUE TITLE
install error?

### ISSUE THREAD

**Issue by DeancuZz** [reverse-shell/routersploit#286]
Eskis-iMac:routersploit Eski$ ./rsf.py
Traceback (most recent call last):
  File "./rsf.py", line 8, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/Users/Eski/routersploit/routersploit/__init__.py", line 1, in <module>
    from routersploit.utils import (
  File "/Users/Eski/routersploit/routersploit/utils/__init__.py", line 19, in <module>
    import requests
ImportError: No module named requests
Eskis-iMac:routersploit Eski$

**Comment by VegetableCat** [comment]
look at 
`ImportError: No module named requests`

you need to install `requests`
in your shell,type:
```sh
pip install requests
```

**Comment by WoHenShuai233** [comment]
@qwqmeow nice兄dei
