### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by bianci5** [reverse-shell/routersploit#99]
Why it didn't work?
`davide@bianci5 ~ $ ./routersploit/rsf.py 
Traceback (most recent call last):
  File "./routersploit/rsf.py", line 3, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/home/davide/routersploit/routersploit/__init__.py", line 1, in <module>
    from routersploit.utils import (
  File "/home/davide/routersploit/routersploit/utils.py", line 36, in <module>
    requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.InsecureRequestWarning)
AttributeError: 'module' object has no attribute 'packages'
`

**Comment by join-us** [comment]
[**requests**](https://github.com/kennethreitz/requests) is missing. Please try to install all packages as following:

```
$ sudo pip install -r requirements.txt
```

**README.md** may be a good friend.

**Comment by bianci5** [comment]
i tryed to do that but this is the error
`error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/gnureadline.so'

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_davide/gnureadline/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-eRMcoE-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_davide/gnureadline
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 66: ordinal not in range(128)
`

**Comment by join-us** [comment]
I guess you need to update pip - `sudo pip install --upgrade pip`.

**Comment by bianci5** [comment]
it works!!!!thanks!!! :-*

**Comment by lucyoa** [comment]
Ok, I'm closing then

**Comment by bianci5** [comment]
it didn t work again

**Comment by bianci5** [comment]
davide@bianci5 ~/routersploit $ ./rsf.py 
Traceback (most recent call last):
  File "./rsf.py", line 3, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/home/davide/routersploit/routersploit/__init__.py", line 1, in <module>
    from routersploit.utils import (
  File "/home/davide/routersploit/routersploit/utils.py", line 19, in <module>
    import requests
ImportError: No module named requests
